from rest_framework import viewsets

from backend.telemetry.models import HealthStatus
from backend.telemetry.models import SensorReading

from .serializers import HealthStatusSerializer
from .serializers import SensorReadingSerializer


class HealthStatusViewSet(viewsets.ReadOnlyModelViewSet):
    # Health statuses are generated by the ML pipeline, so they are read-only from the API
    queryset = HealthStatus.objects.all()
    serializer_class = HealthStatusSerializer


class SensorReadingViewSet(viewsets.ReadOnlyModelViewSet):
    # Readings are ingested via MQTT/Celery worker, so read-only for API access typically
    queryset = SensorReading.objects.all()
    serializer_class = SensorReadingSerializer
