log:
  level: INFO

entryPoints:
  web:
    # http
    address: ':80'

  flower:
    address: ':5555'

http:
  routers:
    web-router:
      rule: 'PathPrefix(`/`)'
      entryPoints:
        - web
      middlewares:
        - csrf
      service: django

    flower-router:
      rule: 'PathPrefix(`/`)'
      entryPoints:
        - flower
      service: flower

    web-media-router:
      rule: 'PathPrefix(`/media/`)'
      entryPoints:
        - web
      middlewares:
        - csrf
      service: django-media

  middlewares:
    csrf:
      headers:
        hostsProxyHeaders: ['X-CSRFToken']

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555

    django-media:
      loadBalancer:
        servers:
          - url: http://nginx:80

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
