name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ["main"]
    paths-ignore: ["docs/**"]
  push:
    branches: ["main"]
    paths-ignore: ["docs/**"]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint & Format Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Install UV Package Manager
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Run Ruff Linter
        run: uv run ruff check backend/ config/

      - name: Run Ruff Formatter
        run: uv run ruff format --check backend/ config/

  test:
    name: Execute Pytest Scenarios
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Scaffold Missing Local Environment Variables
        run: |
          mkdir -p .envs/.local
          echo "DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres" > .envs/.local/.postgres
          echo "POSTGRES_USER=postgres" >> .envs/.local/.postgres
          echo "POSTGRES_PASSWORD=postgres" >> .envs/.local/.postgres
          echo "CELERY_BROKER_URL=redis://redis:6379/0" > .envs/.local/.django
          echo "DJANGO_SETTINGS_MODULE=config.settings.test" >> .envs/.local/.django

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Django Application
        run: docker compose -f docker-compose.local.yml build django

      - name: Run PostgreSQL Database Migrations
        run: docker compose -f docker-compose.local.yml run --rm django python manage.py migrate

      - name: Trigger Pytest Automation Suite
        run: docker compose -f docker-compose.local.yml run --rm django pytest

      - name: Tear Down Docker Environment
        if: always()
        run: docker compose -f docker-compose.local.yml down -v
